Converted everything to hooks and to styled-components
tcoldx/crypto-app pull request #10
Opened 2021-12-09 19:52 UTC by tcoldx

2021-12-09 22:50 UTC, yoloOnTheBattlefield requested changes

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/Pages/Coin/Coin.js
> +  } */
remove old code

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/Pages/Coin/Coin.js
> +            ></p>
why not:
```
<div
              dangerouslySetInnerHTML={{
                __html: coin.description.en,
              }}
            />```

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/Pages/Home/Home.js
> +import CoinList from "../../components/CoinList/index";
setup your folder structure bro

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/components/CoinChart/CoinChart.js
> +`;
styles should be in a separate file

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/components/CoinChart/CoinChart.js
> +        {/*<CoinLegendTwo currency={props.currency} />*/}
do you need this?

2021-12-09 22:50 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +} from "../CoinTable/CoinTable.styles";
setup your folder structure

2021-12-11 02:23 UTC, merged

2021-12-11 18:28 UTC, tcoldx reviewed
changed some of the files around and fixed the folder structure

2021-12-12 14:11 UTC, yoloOnTheBattlefield commented on src/App.js
> +import { Home, Coin, Portfolio } from "Pages";
`pages` should be lower case, you will have git problems after renaming
https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git

2021-12-12 14:11 UTC, yoloOnTheBattlefield commented on src/Pages/Coin/Coin.styles.js
> +`;
some variables have new line, some don't. choose one

2021-12-12 14:11 UTC, yoloOnTheBattlefield commented on src/Pages/Home/Home.js
> +import CoinList from "components/CoinList/CoinList";
import { CoinChart, CoinList } from 'components'